name: Build Nugets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: msbuild /t:Restore /p:Configuration=Release CLanguage.sln
    - name: Build
      run: msbuild /p:Configuration=Release CLanguage/CLanguage.csproj
    - name: Build Test
      run: msbuild /p:Configuration=Release CLanguageTests/CLanguageTests.csproj
    - name: Build Mac Editor
      run: msbuild /p:Configuration=Release Editor/Mac/CLanguage.Editor.Mac.csproj
    - name: Build iOS Editor
      run: msbuild /p:Configuration=Release Editor/iOS/CLanguage.Editor.iOS.csproj
