name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true
          lfs: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            global-json-file: global.json

      - name: Install Workloads
        run: dotnet workload restore CLanguage.sln
